openapi: 3.0.0

info:
  title: Teamsykmelding-mock-backend API
  description: API for teamsykmelding-mock-backend.
  version: 1.0.0
servers:
  - url: 'https://teamsykmelding-mock-backend.dev.intern.nav.no'
paths:
  /narmesteleder/opprett:
    post:
      operationId: opprettNarmesteleder
      tags:
        - Narmesteleder
      summary: Opprett nærmeste leder-kobling
      requestBody:
        $ref: '#/components/requestBodies/OpprettNarmestelederRequestBody'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal server error
  /narmesteleder/{orgnummer}:
    delete:
      operationId: nullstillNarmesteleder
      tags:
        - Narmesteleder
      summary: Bryter nærmeste leder-kobling for ansatt og orgnummer
      parameters:
        - $ref: '#/components/parameters/Orgnummer'
        - $ref: '#/components/parameters/SykmeldtFnr'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal server error
  /sykmelding/opprett:
    post:
      operationId: opprettSykmelding
      tags:
        - Sykmelding
      summary: Opprett sykmelding
      requestBody:
        $ref: '#/components/requestBodies/SykmeldingRequestBody'
      responses:
        '200':
          description: Ok
        '500':
          description: Internal server error
  /sykmelding/regelsjekk:
    post:
      operationId: sjekkSykmelding
      tags:
        - Sykmelding
      summary: Sjekk sykmelding mot regler
      requestBody:
        $ref: '#/components/requestBodies/SykmeldingRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/ValidationResultResponse'
        '500':
          description: Internal server error
  /sykmeldinger:
    delete:
      operationId: slettSykmeldinger
      tags:
        - Sykmelding
      summary: Slett sykmeldinger for fnr
      parameters:
        - $ref: '#/components/parameters/SykmeldtFnr'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal server error
  /legeerklaering/opprett:
    post:
      operationId: opprettLegeerklaering
      tags:
        - Legeerklaering
      summary: Opprett legeerklæring
      requestBody:
        $ref: '#/components/requestBodies/LegeerklaeringRequestBody'
      responses:
        '200':
          description: Ok
        '500':
          description: Internal server error
  /papirsykmelding/opprett:
    post:
      operationId: opprettPapirsykmelding
      tags:
        - Papirsykmelding
      summary: Opprett papirsykmelding
      requestBody:
        $ref: '#/components/requestBodies/PapirsykmeldingRequestBody'
      responses:
        '200':
          description: Ok
        '500':
          description: Internal server error
  /papirsykmelding/utenlandsk/opprett:
    post:
      operationId: opprettUtenlandskPapirsykmelding
      tags:
        - Papirsykmelding
      summary: Opprett utenlandsk papirsykmelding
      parameters:
        - $ref: '#/components/parameters/SykmeldtFnr'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal server error

components:
  requestBodies:
    OpprettNarmestelederRequestBody:
      description: "Opprett nærmeste leder-kobling"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OpprettNarmestelederRequest'
    SykmeldingRequestBody:
      description: "Opprett sykmelding"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SykmeldingRequest'
    LegeerklaeringRequestBody:
      description: "Opprett legeerklæring"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LegeerklaeringRequest'
    PapirsykmeldingRequestBody:
      description: "Opprett papirsykmelding"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PapirsykmeldingRequest'
  responses:
    ValidationResultResponse:
      description: "Resultat av regelsjekk"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationResult'
  parameters:
    Orgnummer:
      description: Bedriftens orgnummer
      name: orgnummer
      in: path
      required: true
      schema:
        type: string
      example: '974600951'
    SykmeldtFnr:
      description: fnr for den sykmeldte
      name: Sykmeldt-Fnr
      in: header
      required: true
      schema:
        type: string

  schemas:
    Date:
      type: string
      format: date
    OpprettNarmestelederRequest:
      type: object
      properties:
        ansattFnr:
          type: string
        lederFnr:
          type: string
        orgnummer:
          type: string
        mobil:
          type: string
        epost:
          type: string
        forskutterer:
          type: boolean
        aktivFom:
          $ref: '#/components/schemas/Date'
      required:
        - ansattFnr
        - lederFnr
        - orgnummer
        - mobil
        - epost
        - forskutterer
        - aktivFom
    SykmeldingPeriode:
      type: object
      properties:
        fom:
          $ref: '#/components/schemas/Date'
        tom:
          $ref: '#/components/schemas/Date'
        type:
          type: string
          enum:
            - AVVENTENDE
            - GRADERT_20
            - GRADERT_40
            - GRADERT_50
            - GRADERT_60
            - GRADERT_80
            - GRADERT_REISETILSKUDD
            - HUNDREPROSENT
            - BEHANDLINGSDAGER
            - BEHANDLINGSDAG
            - REISETILSKUDD
      required:
        - fom
        - tom
        - type
    SykmeldingRequest:
      type: object
      properties:
        fnr:
          type: string
        fnrLege:
          type: string
          example: '01117302624'
        herId:
          type: string
        hprNummer:
          type: string
          example: '7125186'
        syketilfelleStartdato:
          $ref: '#/components/schemas/Date'
        diagnosekode:
          type: string
        diagnosekodesystem:
          type: string
          example: 'icd10'
        annenFraverGrunn:
          type: string
          enum:
            - GODKJENT_HELSEINSTITUSJON
            - BEHANDLING_FORHINDRER_ARBEID
            - ARBEIDSRETTET_TILTAK
            - MOTTAR_TILSKUDD_GRUNNET_HELSETILSTAND
            - NODVENDIG_KONTROLLUNDENRSOKELSE
            - SMITTEFARE
            - ABORT
            - UFOR_GRUNNET_BARNLOSHET
            - DONOR
            - BEHANDLING_STERILISERING
        perioder:
          type: array
          items:
            $ref: '#/components/schemas/SykmeldingPeriode'
        behandletDato:
          $ref: '#/components/schemas/Date'
        kontaktDato:
          $ref: '#/components/schemas/Date'
        begrunnIkkeKontakt:
          type: string
        vedlegg:
          type: boolean
        virksomhetsykmelding:
          type: boolean
        utdypendeOpplysninger:
          type: string
          enum:
            - INGEN
            - UKE_7
            - UKE_17
            - UKE_39
        regelsettVersjon:
          type: string
      required:
        - fnr
        - fnrLege
        - syketilfelleStartdato
        - diagnosekode
        - diagnosekodesystem
        - perioder
        - behandletDato
        - vedlegg
        - virksomhetsykmelding
        - utenUtdypendeOpplysninger
    LegeerklaeringRequest:
      type: object
      properties:
        fnr:
          type: string
        fnrLege:
          type: string
        diagnosekode:
          type: string
        diagnosekodesystem:
          type: string
          example: 'icd10'
        statusPresens:
          type: string
        vedlegg:
          type: boolean
      required:
        - fnr
        - fnrLege
        - diagnosekode
        - diagnosekodesystem
        - vedlegg
    PapirsykmeldingRequest:
      type: object
      properties:
        fnr:
          type: string
        hprNummer:
          type: string
          example: '7125186'
        syketilfelleStartdato:
          $ref: '#/components/schemas/Date'
        behandletDato:
          $ref: '#/components/schemas/Date'
        diagnosekode:
          type: string
        diagnosekodesystem:
          type: string
          example: 'icd10'
        perioder:
          type: array
          items:
            $ref: '#/components/schemas/SykmeldingPeriode'
        utenOcr:
          type: boolean
      required:
        - fnr
        - hprNummer
        - syketilfelleStartdato
        - behandletDato
        - diagnosekode
        - diagnosekodesystem
        - perioder
        - utenOcr
    ValidationResult:
      type: object
      required:
        - status
        - ruleHits
      properties:
        status:
          $ref: '#/components/schemas/Status'
        ruleHits:
          type: array
          items:
            $ref: '#/components/schemas/RuleInfo'
    Status:
      type: string
      enum: [ OK, MANUAL_PROCESSING, INVALID ]
    RuleInfo:
      type: object
      required:
        - messageForSender
        - messageForUser
        - ruleName
        - ruleStatus
      properties:
        messageForSender:
          type: string
        messageForUser:
          type: string
        ruleName:
          type: string
        ruleStatus:
          $ref: '#/components/schemas/Status'
