apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: teamsykmelding-mock-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 700m
      memory: 2048Mi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: false
  ingresses:
    - "https://teamsykmelding-mock-backend.intern.dev.nav.no"
  webproxy: false
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      rules:
        - application: syfosmregister
        - application: syfosmregler
        - application: syfosmpapirregler
        - application: syfohelsenettproxy
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: dokarkiv.dev-fss-pub.nais.io
        - host: oppgave-q1.dev-fss-pub.nais.io
        - host: b27apvl221.preprod.local
          ports:
            - name: mq
              port: 1413
    inbound:
      rules:
        - application: teamsykmelding-mock
          namespace: teamsykmelding
          cluster: dev-gcp
  envFrom:
    - secret: mockbackend-secrets
  secureLogs:
    enabled: true
  env:
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: MQ_HOST_NAME
      value: b27apvl221.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQLS03
    - name: MQ_CHANNEL_NAME
      value: Q1_SYKMELDINGMOCK
    - name: DOKARKIV_URL
      value: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOKARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
    - name: SYFOSMREGISTER_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmregister/.default
    - name: SYFOSMREGLER_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmregler/.default
    - name: SYFOSMPAPIRREGLER_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmpapirregler/.default
    - name: NORSKHELSENETT_SCOPE
      value: api://dev-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: OPPGAVE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io/api/v1/oppgaver
