name: merge-dependabot-pr
on:
  workflow_dispatch:
  schedule:
    - cron: ' 0 7 * * 1'

jobs:
  merge-dependabot-pr:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/merge-dependabot-pr.yaml@main
    permissions:
      actions: write
      checks: read
      contents: write
      pull-requests: write
      statuses: read
